import numpy as np
import os
import sys
from utils import normalise_sim_filename

# Add parent directory to path
sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
)


def test_sim_data():
    """
    Test data generated by simulations/run_sims.py
    is the same as the data generated by the same
    script in the colab notebook for all sim types.
    """
    # Load all .npy files in sim_data
    repo_sim_data = {}
    for file in os.listdir("sim_data"):
        if file.endswith(".npy"):
            normalised_name = normalise_sim_filename(file)
            repo_sim_data[normalised_name] = np.load(f"sim_data/{file}")

    # Load all .npy files in colab_sim_data
    colab_sim_data = {}
    for file in os.listdir("colab_sim_data"):
        if file.endswith(".npy"):
            normalised_name = normalise_sim_filename(file)
            colab_sim_data[normalised_name] = np.load(f"colab_sim_data/{file}")

    # Ensure both sets have the same simulations
    assert set(repo_sim_data.keys()) == set(
        colab_sim_data.keys()
    ), "Mismatch in simulation sets"

    # Compare the data
    for key in repo_sim_data.keys():
        repo_data = repo_sim_data[key]
        colab_data = colab_sim_data[key]
        print(f"Comparing {key}")
        assert np.allclose(repo_data, colab_data), f"Data mismatch for {key}"

    print("All data is the same!")


test_sim_data()
