output_dir: test_runs/spring_2d/l1/test_pruned
tqdm: true
quick_test: false
save_messages: true
message_save_limit: 100000
prune_outliers: 0
data_dir: data/test_data_hpc_reproduce/spring_2d
test_batch_size: 1024
model_weights_path: train_runs/pruned_spring_2d/l1/model_weights/best_model.pt
model: gnn
model_params:
  n_f: 6
  msg_dim: 100
  ndim: 2
  hidden: 300
  aggr: add
  symbolic_edge_pkl_path: false

loss: maeloss+l1reg
loss_params:
  reg_weight: 0.01
