name: vj279_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - black
  - flake8
  - pre-commit
  - pytest
  - jax
  - jaxlib
  - matplotlib
  - matplotlib-inline
  - matplotlib-venn
  - numpy
  - tqdm
  - torch
  - celluloid
  - pip
  - pip:
    - icecream
    - torch_scatter
    - torch_sparse
    - torch_geometric
    - wandb
    - accelerate
    - pandas
    - imageio

