name: vj279_project_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - black
  - flake8
  - pre-commit
  - pytest
  - matplotlib
  - matplotlib-inline
  - matplotlib-venn
  - numpy
  - tqdm
  - celluloid
  - pip
  - pip:
    - icecream
    - torch
    - jax
    - jaxlib
    - wandb
    - accelerate
    - pandas
    - imageio
    - pysr

