# Test configuration file for the GNN model

# General settings
output_dir: '../rds/hpc-work/test_runs/half_size/spring_2d/kl'  # Directory to save outputs (results, logs, etc.)
tqdm: false                      # Use tqdm for progress bars - set to false for HPC as it creates massive logs
save_messages: true              # Save messages to the output directory
message_save_limit: 100000       # Limit for saving messages to avoid large file sizes

# Data settings
data_dir: '../rds/hpc-work/test_data/spring_2d'  # Root directory for the test dataset
test_batch_size: 1024              # Batch size for testing

# Model settings
model_weights_dir: '../rds/hpc-work/train_runs/half_size/spring_2d/bottleneck/model_weights' # Directory containing model weights
model: vargnn                       # Model name (should match a model in model_factory)
model_params:                    # Parameters for the model initialization
  n_f: 6                         # Number of features
  msg_dim: 100                     # Message dimension
  ndim: 2                        # Node dimension
  hidden: 300                    # Hidden layer size
  aggr: 'add'                    # Aggregation method

# Loss settings
loss: 'loss+klreg'               # Loss function name (should match a loss in loss_factory)
loss_params:                     # Parameters for the loss function initialization
  reg_weight: 1                  # Weight for L1 regularization
