data_dir: ../rds/hpc-work/test_data/r1_3d
loss: loss+l1reg
loss_params:
  reg_weight: 0
message_save_limit: 100000
model: gnn
model_params:
  aggr: add
  hidden: 300
  msg_dim: 100
  n_f: 8
  ndim: 3
model_weights_path: ../rds/hpc-work/train_runs/half_size/r1_3d/standard/model_weights/best_model.pt
output_dir: ../rds/hpc-work/test_runs/half_size/r1_3d/standard
save_messages: true
test_batch_size: 1024
tqdm: false
