output_dir: test_runs/r2_3d_200/l1
tqdm: true
save_messages: true
quick_test: false
message_save_limit: 100000
data_dir: data/main_dataset/r2_3d
test_batch_size: 1024
model_weights_path: ../train_runs/pruned/r2_3d_200/l1/model_weights/best_model.pt
model: gnn
prune_outliers: 0
model_params:
  n_f: 8
  msg_dim: 100
  ndim: 3
  hidden: 300
  aggr: add
loss: maeloss+l1reg
loss_params:
  reg_weight: 0
