output_dir: ../rds/hpc-work/test_runs/pruned_models/spring_2d/standard
tqdm: false
save_messages: true
message_save_limit: 100000
data_dir: ../rds/hpc-work/local_datasets/spring_2d
test_batch_size: 1024
model_weights_path: ../rds/hpc-work/train_runs/pruned_runs/spring_2d/standard/model_weights/best_model.pt
model: gnn
model_params:
  n_f: 6
  msg_dim: 100
  ndim: 2
  hidden: 300
  aggr: add
loss: maeloss+l1reg
loss_params:
  reg_weight: 0
