output_dir: <Insert>
tqdm: true
quick_test: false
save_messages: true
message_save_limit: 1000
data_dir: <Insert>
test_batch_size: 1024
prune_outliers: 99.99
model_weights_path: <Insert>
model: gnn
model_params:
  n_f: 6
  msg_dim: 2
  ndim: 2
  hidden: 300
  aggr: add
loss: maeloss+l1reg
loss_params:
  reg_weight: 0

